docker:
  image: yegor256/blog
assets:
  secrets.yml: "zerocracy/home#assets/blog/secrets.yml"
  id_rsa: "zerocracy/home#assets/blog/id_rsa"
  id_rsa.pub: "zerocracy/home#assets/blog/id_rsa.pub"
install: |
  bundle install
deploy:
  script: |
    export JEKYLL_ENV=production
    rake
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git config --global user.email "rultor@yegor256.com"
    git config --global user.name "Rultor"
    jgd
