scss_files: 'css/**/*.scss'

exclude: 'css/_icons.scss'

linters:
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  ImportantRule:
    enabled: false
  ColorVariable:
    exclude:
      - 'css/_ico.scss'
