scss_files: '**/*.scss'

exclude: 'css/layout.scss'

linters:
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  ImportantRule:
    enabled: false
  ColorVariable:
    exclude:
      - '_sass/_ico.scss'
