language: ruby
branches:
  only:
  - master
install:
- travis_retry sudo apt-get update -y
- travis_retry sudo apt-get install -y graphviz
- travis_retry sudo apt-get install -y gnuplot
- wget --retry-connrefused --no-check-certificate http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb
- sudo dpkg -i plantuml_7707-1_all.deb
- rm -rf plantuml_7707-1_all.deb
- travis_retry bundle install
- travis_retry npm install phantomjs -g
- travis_retry npm install casperjs -g
- travis_retry sudo apt-get install -y fontforge
- wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
- unzip woff-code-latest.zip -d sfnt2woff
- cd sfnt2woff
- make
- sudo mv sfnt2woff /usr/local/bin/
- cd ..
- rm -rf sfnt2woff
- travis_retry npm install --global cssshrink
before_install:
- set -e
- openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv
  -in s3cfg.enc -out s3cfg -d
- openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv
  -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh
- chmod 600 ~/.ssh/id_rsa
script:
- set -e
- fontcustom compile _glyphs --output=_temp/icons/ --font-name=icons --templates=scss --no-hash --force --autowidth
- mv _temp/icons/_icons.scss css
- sed -i '' s/font-url\(data:[^\)]+\),//g css/_icons.scss
- sed -i '' s/(?:font-)?url\((?:"|')([^"']+)(?:"|')\)/http://img.teamed.io/yegor256/url('\1')/g css/_icons.scss
- s3cmd --no-progress put _temp/icons/icons.eot --config=s3cfg s3://img.teamed.io/yegor256/icons.eot
- s3cmd --no-progress put _temp/icons/icons.woff --config=s3cfg s3://img.teamed.io/yegor256/icons.woff
- s3cmd --no-progress put _temp/icons/icons.ttf --config=s3cfg s3://img.teamed.io/yegor256/icons.ttf
- _test/test_casperjs.sh
- jekyll build
#- _test/ping_links.sh
- _test/w3c_validate.sh
- _test/test_excerps.sh
- _test/test_pages_existence.sh
- for i in $(ls js/*.js); do jslint $i; done
- git config --global user.email "travis@teamed.io"
- git config --global user.name "travis"
- jgd -u git@github.com:yegor256/blog.git
