language: ruby
branches:
  only:
    - master
install:
  - sudo apt-get install -y graphviz
  - wget --retry-connrefused http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb
  - sudo dpkg -i plantuml_7707-1_all.deb
  - bundle install
  - npm install phantomjs -g
  - npm install casperjs -g
  - sudo apt-get install -y fontforge
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff
  - cd sfnt2woff
  - make
  - sudo mv sfnt2woff /usr/local/bin/
  - cd ..
env:
  global:
    - secure: "XSO7qwYvHZ4C29uIVodtvbI1L140VE12NPBBkkufCQSYlDupFPbjOx8OsEDCpnfcK0NSqAEeIAVNO0BIcrzE3cBzcLU8LfLCejOvZIou79R8k6ZTOsAG/7XLPOOk1tPCbKC3IVo3ouTXFFCK6Xye9GE2ymffvpGpu/cluahsBck="
script:
  - set -e
  - git config --global user.email "travis@teamed.io"
  - git config --global user.name "travis"
  - _test/run.sh
  - for i in $(ls js/*.js); do jslint $i; done
  - jgd -u https://yegor256:$PASSWORD@github.com/yegor256/blog.git

