language: ruby
branches:
  only:
  - master
install:
- set -e
- wget --retry-connrefused --no-check-certificate http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb
- sudo dpkg -i plantuml_7707-1_all.deb
- rm -rf plantuml_7707-1_all.deb
- travis_retry bundle install
- wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
- unzip woff-code-latest.zip -d sfnt2woff
- cd sfnt2woff
- make
- sudo mv sfnt2woff /usr/local/bin/
- cd ..
- rm -rf sfnt2woff
- git clone https://github.com/htacg/tidy-html5.git
- cd tidy-html5/build/cmake
- git checkout 5.1.9
- cmake ../..
- make
- sudo make install
- cd ../..
before_install:
- set -e
- export DEBIAN_FRONTEND=noninteractive
- travis_retry sudo apt-get remove -y cmake
- travis_retry sudo apt-get remove -y postgresql
- travis_retry sudo apt-get install software-properties-common
- travis_retry sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
- travis_retry sudo apt-get update -qq
- travis_retry sudo apt-get upgrade -qq -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
- travis_retry sudo apt-get install -y cmake
- travis_retry sudo apt-get install -y aspell
- travis_retry sudo apt-get install -y libxml2-utils
- travis_retry sudo apt-get install -y graphviz
- travis_retry sudo apt-get install -y gnuplot
- travis_retry sudo apt-get install -y s3cmd
- travis_retry sudo apt-get install -y fontforge
- travis_retry npm install phantomjs -g
- travis_retry npm install casperjs -g
- travis_retry npm install --global cssshrink
- openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in s3cfg.enc -out s3cfg -d
- openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh
- chmod 600 ~/.ssh/id_rsa
script:
- set -e
- _test/test_casperjs.sh
- jekyll build
- _test/test_grammar.sh
- _test/test_orphans.sh
- _test/test_keywords.sh
- _test/ping_links.sh
- _test/w3c_validate.sh
- _test/test_excerps.sh
- _test/test_pages_existence.sh
- for i in $(ls js/*.js); do jslint $i; done
- git config --global user.email "travis@teamed.io"
- git config --global user.name "travis"
- jgd -u git@github.com:yegor256/blog.git

