language: ruby
rvm:
  - 2.2.2
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules
    - vendor/bundle
    - _tidy-html5
    - _sfnt2woff
    - _cmake-3.5.1
env:
  global:
    secure: qR4hHnevbFEXIUt4NNOvW5NXyck+F7PQWbp1RW8jyufR6CJFeCRvc4ZtaiIf4N2g7zQK6M98BM/IuUu9qBhL4k9lUV9XMuOX3mx4GXFqGla3JPvi9lLHJf3zd0QHp0Ekxh9ewRqKCEGbSvlXflEGkRN+dkBII0eUMBoQxr8DLzk=
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - build-essential
      - graphviz
      - gnuplot
      - s3cmd
      - fontforge
      - liblapack-dev
before_install: |
  set -e
  git config --global user.email "travis@yegor256.com"
  git config --global user.name "travis"
  openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in s3cfg.enc -out s3cfg -d
  openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in id_rsa.enc -out id_rsa -d
  mv id_rsa ~/.ssh
  chmod 600 ~/.ssh/id_rsa
  function keep_alive() {
    while true; do
      echo -en "\a"
      sleep 5
    done
  }
  keep_alive &
install:
  - set -e
  - 'travis_retry sudo _travis/install_cmake.sh && sudo apt-get install -y libxml2-utils'
  - travis_retry npm install cssshrink@0.0.5
  - travis_retry sudo _travis/install_plantuml.sh
  - travis_retry sudo _travis/install_sfnt2woff.sh
  - travis_retry sudo _travis/install_tidy.sh
  - travis_retry bundle install
  - fontcustom --version
  - travis_retry gem install jgd -v 1.6.5
  - gnuplot --version
script:
  - set -e
  - export JEKYLL_ENV=production
  - rake clean
  - rake
  - jgd -u git@github.com:yegor256/blog.git
