language: ruby
branches:
  only:
  - master
before_install:
- set -e
- git config --global user.email "travis@teamed.io"
- git config --global user.name "travis"
- openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in s3cfg.enc -out s3cfg -d
- openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh
- chmod 600 ~/.ssh/id_rsa
install:
- set -e
- travis_retry sudo apt-get update -y
- travis_retry sudo apt-get install -y build-essential
- travis_retry _travis/install_cmake.sh
- travis_retry sudo apt-get install -y libxml2-utils
- travis_retry sudo apt-get install -y graphviz
- travis_retry sudo apt-get install -y gnuplot
- travis_retry sudo apt-get install -y s3cmd
- travis_retry sudo apt-get install -y fontforge
- travis_retry npm install --global phantomjs
- travis_retry npm install --global casperjs
- travis_retry npm install --global cssshrink
- travis_retry _travis/install_plantuml.sh
- travis_retry _travis/install_sfnt2woff.sh
- travis_retry _travis/install_tidy.sh
- travis_retry bundle install
script:
- set -e
- _travis/test_casperjs.sh
- rm -rf _site
- jekyll build
- _travis/test_grammar.sh
- _travis/test_orphans.sh
# - _travis/test_keywords.sh
- _travis/test_links.sh
- _travis/test_w3c.sh
- _travis/test_excerps.sh
- _travis/test_pages_existence.sh
- _travis/test_jslint.sh
- jgd -u git@github.com:yegor256/blog.git

