language: ruby
branches:
  only:
    - master
install:
  - sudo apt-get install -y graphviz
  - wget --retry-connrefused http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb
  - sudo dpkg -i plantuml_7707-1_all.deb
  - rm -rf plantuml_7707-1_all.deb
  - bundle install
  - npm install phantomjs -g
  - npm install casperjs -g
  - sudo apt-get install -y fontforge
  - wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  - unzip woff-code-latest.zip -d sfnt2woff
  - cd sfnt2woff
  - make
  - sudo mv sfnt2woff /usr/local/bin/
  - cd ..
  - rm -rf sfnt2woff
  - npm install --global cssshrink
before_install:
  - openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in id_rsa.enc -out id_rsa -d
  - mkdir -p ~/.ssh
  - mv id_rsa ~/.ssh
  - chmod -R 600 ~/.ssh
script:
  - set -e
  - set -x
  - _test/test_casperjs.sh
  - jekyll build
  - _test/ping_links.sh
  - _test/w3c_validate.sh
  - for i in $(ls js/*.js); do jslint $i; done
  - git config --global user.email "travis@teamed.io"
  - git config --global user.name "travis"
  - jgd
