language: ruby
branches:
  only:
    - master
install: |
  sudo apt-get install -y graphviz
  wget --retry-connrefused http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb
  sudo dpkg -i plantuml_7707-1_all.deb
  bundle install
  npm install phantomjs -g
  npm install casperjs -g
  sudo apt-get install -y fontforge
  sudo apt-get install -y ttfautohint
  wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  unzip woff-code-latest.zip -d sfnt2woff
  cd sfnt2woff
  make
  sudo mv sfnt2woff /usr/local/bin/
  cd ..
  gem install fontcustom
env:
  global:
    - secure: "YRF2hq6GI07WDf8uzPgRZ72MF0/m+KRLXOvLFApzliPGav86wMdMBnUlb2TnbneOIjnZsFnivVTi0nOmhBJu/tOTnLdXUn96smKg60hHuQOqZYohv0Kbzl5SU0uDfN50q2inXxgd7xSH3D0zCMge8TacWzrp233NcjncArsYyoU="
script: |
  git config --global user.email "travis@teamed.io"
  git config --global user.name "Travis"
  _test/run.sh && jslint js/all.js && jgd -u https://yegor256:$PASSWORD@github.com/yegor256/blog.git

