language: ruby
rvm:
  - 2.0.0
sudo: required
cache: bundler
branches:
  only:
    - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - build-essential
      - graphviz
      - gnuplot
      - s3cmd
      - fontforge
      - liblapack-dev
before_install:
  - set -e
  - git config --global user.email "travis@teamed.io"
  - git config --global user.name "travis"
  - openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in s3cfg.enc -out s3cfg -d
  - openssl aes-256-cbc -K $encrypted_b3d57c6f91bb_key -iv $encrypted_b3d57c6f91bb_iv -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
install:
  - set -e
  - travis_retry _travis/install_cmake.sh; sudo apt-get install -y libxml2-utils
  - travis_retry npm install --global phantomjs
  - travis_retry npm install --global casperjs
  - travis_retry npm install --global cssshrink
  - travis_retry _travis/install_plantuml.sh
  - travis_retry _travis/install_sfnt2woff.sh
  - travis_retry _travis/install_tidy.sh
  - travis_retry bundle install
  - travis_retry gem install fontcustom -v 1.3.8
  - travis_retry gem install scss-lint -v 0.38.0
  - travis_retry gem install w3c_validators -v 1.2
  - travis_retry gem install jslint -v 1.2.0
  - travis_retry gem install jgd -v 1.6.5
script:
  - set -e
  - gnuplot --version
  - fontcustom --version
  - _travis/test_casperjs.sh
  - rm -rf _site
  - jekyll build
  - "grep -R --files-with-match xxx _site; if [ $? == 0 ]; then exit -1; fi"
  - _travis/test_grammar.sh
  - _travis/test_orphans.sh
  # - _travis/test_keywords.sh
  - _travis/test_links.sh
  - _travis/test_w3c.sh
  - _travis/test_excerps.sh
  - _travis/test_pages_existence.sh
  - _travis/test_jslint.sh
  - tail -n +3 css/layout.scss > _temp/layout.scss
  - scss-lint -c .scss-lint.yml
  - jgd -u git@github.com:yegor256/blog.git

