name: yegor256.com
url: http://www.yegor256.com
title: "Yegor Bugayenko"
author:
  name: "Yegor Bugayenko"
  email: yegor@teamed.io
description: "Yegor Bugayenko"
copyright: "(c) Yegor Bugayenko, 2014-2016"
encoding: utf-8
timezone: America/San_Francisco
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
permalink: :year/:month/:day/:title.html
paginate: 10
paginate_path: "p/:num"
excerpt_separator: <!--more-->

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-plantuml
  - jekyll-sitemap
  - jekyll-related-posts

# see https://github.com/alfanick/jekyll-related-posts
related:
  max_count: 5
  min_score: 0.1
  accuracy: 0.75

feed:
  title: yegor256.com
  subtitle: Programming Blog
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

# see https://github.com/pattex/jekyll-tagging
tag_page_layout: tag-index
tag_page_dir: tag
