name: yegor256.com
markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: :year/:month/:day/:title.html

# https://github.com/agelber/jekyll-rss
url: http://www.yegor256.com/
rss_name: rss.xml

# see https://github.com/noct/jekyll-sass
gems: ['jekyll-sass']
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false

