name: yegor256.com
title: "Yegor Bugayenko"
author: "Yegor Bugayenko"
description: "Yegor Bugayenko"
copyright: "(c) Yegor Bugayenko, 2014"
encoding: utf-8
timezone: America/San_Francisco
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: :year/:month/:day/:title.html
paginate: 10
paginate_path: "p/:num"
excerpt_separator: <!--more-->

gems: ['jekyll-sass', 'jekyll-plantuml', 'jekyll-press']

# https://github.com/agelber/jekyll-rss
url: http://www.yegor256.com
rss_post_limit: 15

# see https://github.com/noct/jekyll-sass
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

# see https://github.com/stereobooster/jekyll-press
jekyll-press:
  exclude: ['/rss.xml', '/rss-jcg.xml']

# see https://github.com/pattex/jekyll-tagging
tag_page_layout: tag-index
tag_page_dir: tag

# see https://github.com/kinnetica/jekyll-plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/rss.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequence"
  priority_name: "priority"
